const Config = Object.freeze({
  frameworkName: 'Rumble',
  version: '0.11.2',
  defaultCash: 500,
  defaultCard: 5000,
  maxCharacters: 5,
  minimumCharacterAge: 18,
  maintenanceIntervalMs: 60000,
  hungerDecay: 1,
  thirstDecay: 1,
  starvationDamage: 5,
  dehydrationDamage: 5,
  inventoryMaxWeight: 30000,
  inventoryMaxSlots: 40,
  maxItemOperation: 1000,
  deathDeadAfterMs: 60000,
  maxRpcPayloadBytes: 16384,
  maxMetadataBytes: 16000,
  securityLogWindowMs: 10000,
  expectedMigration: 4,
  apiVersion: '1.0',
  environment: 'development',
  slowQueryThresholdMs: 100,
  databaseCircuitFailureThreshold: 5,
  databaseCircuitOpenMs: 3000,
  rpcIdempotencyTtlMs: 30000,
  shutdownTimeoutMs: 5000,
  features: Object.freeze({
    needs: true,
    inventory: true,
    vehicles: true,
    metadata: true,
    money: true,
    characterLock: true,
    idempotentRpc: true,
    queryProfiler: true,
  }),
  adminIdentifier: GetConvar('rumble_admin_identifier', '').trim(),
});
