const Config = Object.freeze({
  frameworkName: 'Rumble',
  version: '0.10.6',
  defaultCash: 500,
  defaultCard: 5000,
  maxCharacters: 5,
  minimumCharacterAge: 18,
  maintenanceIntervalMs: 60000,
  hungerDecay: 1,
  thirstDecay: 1,
  starvationDamage: 5,
  dehydrationDamage: 5,
  inventoryMaxWeight: 30000,
  inventoryMaxSlots: 40,
  maxItemOperation: 1000,
  deathDeadAfterMs: 60000,
  maxRpcPayloadBytes: 16384,
  maxMetadataBytes: 16000,
  securityLogWindowMs: 10000,
  expectedMigration: 3,
  adminIdentifier: GetConvar('rumble_admin_identifier', '').trim(),
});
