declare function on(eventName: string, handler: (...args: any[]) => void): void;
declare function onNet(eventName: string, handler: (...args: any[]) => void): void;
declare function emit(eventName: string, ...args: any[]): void;
declare function emitNet(eventName: string, ...args: any[]): void;
declare function RegisterCommand(
  commandName: string,
  handler: (source: number, args: string[], rawCommand: string) => void,
  restricted: boolean
): void;
declare function PlayerId(): number;
declare function PlayerPedId(): number;
declare function SetMaxWantedLevel(maxWantedLevel: number): void;
declare function ClearPlayerWantedLevel(player: number): void;
declare function SetPlayerWantedLevel(player: number, wantedLevel: number, disableNoMission: boolean): void;
declare function SetPlayerWantedLevelNow(player: number, p2: boolean): void;
declare function SetPoliceIgnorePlayer(player: number, toggle: boolean): void;
declare function SetDispatchCopsForPlayer(player: number, toggle: boolean): void;
declare function EnableDispatchService(dispatchService: number, toggle: boolean): void;
declare function SetCreateRandomCops(toggle: boolean): void;
declare function SetCreateRandomCopsNotOnScenarios(toggle: boolean): void;
declare function SetCreateRandomCopsOnScenarios(toggle: boolean): void;
declare function SetEveryoneIgnorePlayer(player: number, toggle: boolean): void;
declare function SetPlayerCanBeHassledByGangs(player: number, toggle: boolean): void;
declare function SetIgnoreLowPriorityShockingEvents(player: number, toggle: boolean): void;
declare function SetRelationshipBetweenGroups(relationship: number, group1: number, group2: number): void;
declare function GetHashKey(value: string): number;
declare function RequestModel(model: number): void;
declare function HasModelLoaded(model: number): boolean;
declare function SetModelAsNoLongerNeeded(model: number): void;
declare function SetPlayerModel(player: number, model: number): void;
declare function SetPedDefaultComponentVariation(ped: number): void;
declare function ClearAllPedProps(ped: number): void;
declare function ResetEntityAlpha(entity: number): void;
declare function CreateCamWithParams(camName: string, posX: number, posY: number, posZ: number, rotX: number, rotY: number, rotZ: number, fov: number, active: boolean, rotationOrder: number): number;
declare function DoesCamExist(cam: number): boolean;
declare function SetCamActive(cam: number, active: boolean): void;
declare function PointCamAtEntity(cam: number, entity: number, offsetX: number, offsetY: number, offsetZ: number, p5: boolean): void;
declare function RenderScriptCams(render: boolean, ease: boolean, easeTime: number, p3: boolean, p4: boolean): void;
declare function DestroyCam(cam: number, thisScriptCheck: boolean): void;
declare function NetworkResurrectLocalPlayer(x: number, y: number, z: number, heading: number, unk: boolean, changetime: boolean): void;
declare function GetEntityCoords(entity: number, alive?: boolean): [number, number, number];
declare function SetEntityCoordsNoOffset(entity: number, x: number, y: number, z: number, keepTasks: boolean, keepIK: boolean, doWarp: boolean): void;
declare function SetEntityHeading(entity: number, heading: number): void;
declare function GetEntityHeading(entity: number): number;
declare function SetEntityHealth(entity: number, health: number): void;
declare function GetEntityHealth(entity: number): number;
declare function GetEntityMaxHealth(entity: number): number;
declare function SetPedArmour(ped: number, amount: number): void;
declare function GetPedArmour(ped: number): number;
declare function ClearPedTasksImmediately(ped: number): void;
declare function ClearPedBloodDamage(ped: number): void;
declare function ResetPedVisibleDamage(ped: number): void;
declare function SetEntityInvincible(entity: number, toggle: boolean): void;
declare function SetEntityVisible(entity: number, toggle: boolean, unk: boolean): void;
declare function FreezeEntityPosition(entity: number, toggle: boolean): void;
declare function IsEntityDead(entity: number): boolean;
declare function RequestCollisionAtCoord(x: number, y: number, z: number): void;
declare function HasCollisionLoadedAroundEntity(entity: number): boolean;
declare function DoScreenFadeOut(duration: number): void;
declare function DoScreenFadeIn(duration: number): void;
declare function IsScreenFadedOut(): boolean;
declare function ShutdownLoadingScreen(): void;
declare function ShutdownLoadingScreenNui(): void;
declare function SendNuiMessage(jsonString: string): void;
declare function SetNuiFocus(hasFocus: boolean, hasCursor: boolean): void;
declare function RegisterNuiCallbackType(callbackType: string): void;
declare function GetGameplayCamRot(rotationOrder: number): [number, number, number];
declare function GetFrameTime(): number;
declare function DisableControlAction(inputGroup: number, control: number, disable: boolean): void;
declare function IsDisabledControlPressed(inputGroup: number, control: number): boolean;
declare function IsDisabledControlJustPressed(inputGroup: number, control: number): boolean;
declare function SetEntityCollision(entity: number, toggle: boolean, keepPhysics: boolean): void;
declare function SetEntityVelocity(entity: number, x: number, y: number, z: number): void;
declare function GetVehiclePedIsIn(ped: number, lastVehicle: boolean): number;
declare function GetPedInVehicleSeat(vehicle: number, index: number): number;
declare function DoesEntityExist(entity: number): boolean;
declare function SetFocusPosAndVel(x: number, y: number, z: number, offsetX: number, offsetY: number, offsetZ: number): void;
declare function ClearFocus(): void;
declare function GetFirstBlipInfoId(sprite: number): number;
declare function DoesBlipExist(blip: number): boolean;
declare function GetBlipInfoIdCoord(blip: number): [number, number, number];
declare function GetGroundZFor_3dCoord(x: number, y: number, z: number, ignoreWater: boolean): [boolean, number];
declare function GetCurrentResourceName(): string;
declare function setTick(handler: () => void): number;
declare function clearTick(tickId: number): void;

declare function exports(exportName: string, handler: (...args: any[]) => any): void;
declare function GetGameplayCamCoord(): [number, number, number];
declare function StartShapeTestRay(x1: number, y1: number, z1: number, x2: number, y2: number, z2: number, flags: number, entity: number, p8: number): number;
declare function GetShapeTestResult(rayHandle: number): [number, boolean, [number, number, number], [number, number, number], number];
declare function GetEntityModel(entity: number): number;
declare function GetEntityType(entity: number): number;
declare function NetworkGetNetworkIdFromEntity(entity: number): number;
declare function GetPlayerFromServerId(serverId: number): number;
declare function GetPlayerPed(playerId: number): number;
declare function NetworkSetInSpectatorMode(toggle: boolean, playerPed: number): void;
declare function IsModelInCdimage(model: number): boolean;
declare function IsModelAVehicle(model: number): boolean;
declare function CreateVehicle(modelHash: number, x: number, y: number, z: number, heading: number, isNetwork: boolean, netMissionEntity: boolean): number;
declare function SetVehicleOnGroundProperly(vehicle: number): boolean;
declare function SetPedIntoVehicle(ped: number, vehicle: number, seatIndex: number): void;
declare function SetEntityAsMissionEntity(entity: number, scriptHostObject: boolean, grabFromOtherScript: boolean): void;
declare function DeleteEntity(entity: number): void;
declare function GetClosestVehicle(x: number, y: number, z: number, radius: number, modelHash: number, flags: number): number;
declare function GetVehicleNumberPlateText(vehicle: number): string;
declare function GetVehicleEngineHealth(vehicle: number): number;
declare function GetVehicleBodyHealth(vehicle: number): number;
declare function GetVehicleFuelLevel(vehicle: number): number;
declare function NetworkRequestControlOfEntity(entity: number): boolean;
declare function NetworkHasControlOfEntity(entity: number): boolean;
