declare function on(eventName: string, handler: (...args: any[]) => void): void;
declare function RegisterCommand(commandName: string, handler: (source: number, args: string[], rawCommand: string) => void, restricted: boolean): void;
declare function RegisterKeyMapping(commandName: string, description: string, defaultMapper: string, defaultParameter: string): void;
declare function PlayerId(): number;
declare function PlayerPedId(): number;
declare function GetCurrentResourceName(): string;
declare function GetHashKey(value: string): number;
declare function SetMaxWantedLevel(maxWantedLevel: number): void;
declare function ClearPlayerWantedLevel(player: number): void;
declare function SetPlayerWantedLevel(player: number, wantedLevel: number, disableNoMission: boolean): void;
declare function SetPlayerWantedLevelNow(player: number, p2: boolean): void;
declare function SetPoliceIgnorePlayer(player: number, toggle: boolean): void;
declare function SetDispatchCopsForPlayer(player: number, toggle: boolean): void;
declare function EnableDispatchService(dispatchService: number, toggle: boolean): void;
declare function SetCreateRandomCops(toggle: boolean): void;
declare function SetCreateRandomCopsNotOnScenarios(toggle: boolean): void;
declare function SetCreateRandomCopsOnScenarios(toggle: boolean): void;
declare function SetPlayerCanBeHassledByGangs(player: number, toggle: boolean): void;
declare function SetIgnoreLowPriorityShockingEvents(player: number, toggle: boolean): void;
declare function SetRelationshipBetweenGroups(relationship: number, group1: number, group2: number): void;
declare function DoesEntityExist(entity: number): boolean;
declare function IsEntityAPed(entity: number): boolean;
declare function IsPedAPlayer(ped: number): boolean;
declare function IsEntityDead(entity: number): boolean;
declare function IsPedRagdoll(ped: number): boolean;
declare function IsPedInAnyVehicle(ped: number, atGetIn: boolean): boolean;
declare function NetworkGetEntityIsNetworked(entity: number): boolean;
declare function NetworkHasControlOfEntity(entity: number): boolean;
declare function NetworkRequestControlOfEntity(entity: number): boolean;
declare function GetWeaponDamageType(weaponHash: number): number;
declare function ClearPedTasks(ped: number): void;
declare function SetBlockingOfNonTemporaryEvents(ped: number, toggle: boolean): void;
declare function TaskCombatPed(ped: number, targetPed: number, p2: number, p3: number): void;
declare function TaskSmartFleePed(ped: number, fleeTarget: number, distance: number, fleeTime: number, preferPavements: boolean, quitIfOutOfRange: boolean): void;
declare function RequestAnimDict(animDict: string): void;
declare function HasAnimDictLoaded(animDict: string): boolean;
declare function RemoveAnimDict(animDict: string): void;
declare function TaskPlayAnim(ped: number, animDictionary: string, animationName: string, blendInSpeed: number, blendOutSpeed: number, duration: number, flag: number, playbackRate: number, lockX: boolean, lockY: boolean, lockZ: boolean): void;
declare function StopAnimTask(ped: number, animDictionary: string, animationName: string, blendOutSpeed: number): void;
declare function ClearPedSecondaryTask(ped: number): void;
declare function TaskMoveNetworkByName(ped: number, task: string, multiplier: number, allowOverrideCloneUpdate: boolean, animDict: string, flags: number): void;
declare function RequestTaskMoveNetworkStateTransition(ped: number, name: string): void;
declare function SetTaskMoveNetworkSignalFloat(ped: number, signalName: string, value: number): void;
declare function SetTaskMoveNetworkSignalBool(ped: number, signalName: string, value: boolean): void;
declare function GetGameplayCamRelativePitch(): number;
declare function GetGameplayCamRelativeHeading(): number;
declare function SetPedCurrentWeaponVisible(ped: number, visible: boolean, deselectWeapon: boolean, p2: boolean, p3: boolean): void;
declare function SetPedConfigFlag(ped: number, flagId: number, value: boolean): void;
declare function DisableControlAction(padIndex: number, control: number, disable: boolean): void;
declare function setTick(handler: () => void): number;
declare function clearTick(tickId: number): void;

declare function GetSelectedPedWeapon(ped: number): number;
declare function SetCurrentPedWeapon(ped: number, weaponHash: number, equipNow: boolean): void;
declare function IsPauseMenuActive(): boolean;
declare function GetGameplayCamCoord(): [number, number, number];
declare function GetGameplayCamRot(rotationOrder: number): [number, number, number];
declare function GetFinalRenderedCamFov(): number;
declare function GetFrameTime(): number;
declare function CreateCamWithParams(camName: string, posX: number, posY: number, posZ: number, rotX: number, rotY: number, rotZ: number, fov: number, active: boolean, rotationOrder: number): number;
declare function DoesCamExist(cam: number): boolean;
declare function SetCamCoord(cam: number, posX: number, posY: number, posZ: number): void;
declare function SetCamRot(cam: number, rotX: number, rotY: number, rotZ: number, rotationOrder: number): void;
declare function SetCamFov(cam: number, fieldOfView: number): void;
declare function RenderScriptCams(render: boolean, ease: boolean, easeTime: number, p3: boolean, p4: boolean): void;
declare function DestroyCam(cam: number, thisScriptCheck: boolean): void;
