declare function on(eventName: string, handler: (...args: any[]) => void): void;
declare function RegisterCommand(commandName: string, handler: (source: number, args: string[], rawCommand: string) => void, restricted: boolean): void;
declare function RegisterKeyMapping(commandName: string, description: string, defaultMapper: string, defaultParameter: string): void;
declare function PlayerPedId(): number;
declare function RequestAnimDict(animDict: string): void;
declare function HasAnimDictLoaded(animDict: string): boolean;
declare function RemoveAnimDict(animDict: string): void;
declare function TaskPlayAnim(ped: number, animDictionary: string, animationName: string, blendInSpeed: number, blendOutSpeed: number, duration: number, flag: number, playbackRate: number, lockX: boolean, lockY: boolean, lockZ: boolean): void;
declare function StopAnimTask(ped: number, animDictionary: string, animationName: string, blendOutSpeed: number): void;
declare function ClearPedSecondaryTask(ped: number): void;
declare function IsPedInAnyVehicle(ped: number, atGetIn: boolean): boolean;
declare function IsPedRagdoll(ped: number): boolean;
declare function IsEntityDead(entity: number): boolean;
declare function TaskMoveNetworkByName(ped: number, task: string, multiplier: number, allowOverrideCloneUpdate: boolean, animDict: string, flags: number): void;
declare function RequestTaskMoveNetworkStateTransition(ped: number, name: string): void;
declare function SetTaskMoveNetworkSignalFloat(ped: number, signalName: string, value: number): void;
declare function SetTaskMoveNetworkSignalBool(ped: number, signalName: string, value: boolean): void;
declare function GetGameplayCamRelativePitch(): number;
declare function GetGameplayCamRelativeHeading(): number;
declare function SetPedCurrentWeaponVisible(ped: number, visible: boolean, deselectWeapon: boolean, p2: boolean, p3: boolean): void;
declare function SetPedConfigFlag(ped: number, flagId: number, value: boolean): void;
declare function DisableControlAction(padIndex: number, control: number, disable: boolean): void;
declare function setTick(handler: () => void): number;
declare function clearTick(tickId: number): void;
declare function GetCurrentResourceName(): string;
