declare function on(eventName: string, handler: (...args: any[]) => void): void;
declare function onNet(eventName: string, handler: (...args: any[]) => void): void;
declare function emit(eventName: string, ...args: any[]): void;
declare function emitNet(eventName: string, ...args: any[]): void;
declare function RegisterCommand(commandName: string, handler: (source: number, args: string[], rawCommand: string) => void, restricted: boolean): void;
declare function GetCurrentResourceName(): string;
declare function PlayerPedId(): number;
declare function GetEntityCoords(entity: number, alive?: boolean): [number, number, number];
declare function GetEntityHeading(entity: number): number;
declare function DoesEntityExist(entity: number): boolean;
declare function GetHashKey(value: string): number;
declare function RequestModel(model: number): void;
declare function HasModelLoaded(model: number): boolean;
declare function SetModelAsNoLongerNeeded(model: number): void;
declare function IsModelInCdimage(model: number): boolean;
declare function IsModelAVehicle(model: number): boolean;
declare function CreateVehicle(modelHash: number, x: number, y: number, z: number, heading: number, isNetwork: boolean, netMissionEntity: boolean): number;
declare function SetVehicleOnGroundProperly(vehicle: number): boolean;
declare function SetEntityAsMissionEntity(entity: number, scriptHostObject: boolean, grabFromOtherScript: boolean): void;
declare function SetVehicleNumberPlateText(vehicle: number, text: string): void;
declare function NetworkGetNetworkIdFromEntity(entity: number): number;
declare function SetNetworkIdCanMigrate(netId: number, toggle: boolean): void;
declare function DeleteEntity(entity: number): void;
declare function NetworkRequestControlOfEntity(entity: number): boolean;
declare function NetworkHasControlOfEntity(entity: number): boolean;
declare function GetOffsetFromEntityInWorldCoords(entity: number, offsetX: number, offsetY: number, offsetZ: number): [number, number, number];
declare function CreateObject(modelHash: number, x: number, y: number, z: number, isNetwork: boolean, netMissionEntity: boolean, dynamic: boolean): number;
declare function PlaceObjectOnGroundProperly(object: number): boolean;
declare function FreezeEntityPosition(entity: number, toggle: boolean): void;
declare function SetEntityCollision(entity: number, toggle: boolean, keepPhysics: boolean): void;
declare function AttachEntityToEntity(entity1: number, entity2: number, boneIndex: number, xPos: number, yPos: number, zPos: number, xRot: number, yRot: number, zRot: number, p9: boolean, useSoftPinning: boolean, collision: boolean, isPed: boolean, vertexIndex: number, fixedRot: boolean): void;
declare function GetPedBoneIndex(ped: number, boneId: number): number;
declare function RequestAnimDict(animDict: string): void;
declare function HasAnimDictLoaded(animDict: string): boolean;
declare function RemoveAnimDict(animDict: string): void;
declare function TaskPlayAnim(ped: number, animDictionary: string, animationName: string, blendInSpeed: number, blendOutSpeed: number, duration: number, flag: number, playbackRate: number, lockX: boolean, lockY: boolean, lockZ: boolean): void;
declare function TaskStartScenarioInPlace(ped: number, scenarioName: string, unkDelay: number, playEnterAnim: boolean): void;
declare function ClearPedTasks(ped: number): void;
declare function IsControlJustPressed(inputGroup: number, control: number): boolean;
declare function DisableControlAction(inputGroup: number, control: number, disable: boolean): void;
declare function DrawMarker(type: number, posX: number, posY: number, posZ: number, dirX: number, dirY: number, dirZ: number, rotX: number, rotY: number, rotZ: number, scaleX: number, scaleY: number, scaleZ: number, red: number, green: number, blue: number, alpha: number, bobUpAndDown: boolean, faceCamera: boolean, p19: number, rotate: boolean, textureDict: string | null, textureName: string | null, drawOnEnts: boolean): void;
declare function SetTextFont(fontType: number): void;
declare function SetTextScale(scale: number, size: number): void;
declare function SetTextColour(red: number, green: number, blue: number, alpha: number): void;
declare function SetTextCentre(align: boolean): void;
declare function SetTextOutline(): void;
declare function BeginTextCommandDisplayText(text: string): void;
declare function AddTextComponentSubstringPlayerName(text: string): void;
declare function EndTextCommandDisplayText(x: number, y: number): void;
declare function AddBlipForCoord(x: number, y: number, z: number): number;
declare function AddBlipForEntity(entity: number): number;
declare function DoesBlipExist(blip: number): boolean;
declare function RemoveBlip(blip: number): void;
declare function SetBlipSprite(blip: number, spriteId: number): void;
declare function SetBlipColour(blip: number, color: number): void;
declare function SetBlipScale(blip: number, scale: number): void;
declare function SetBlipAsShortRange(blip: number, toggle: boolean): void;
declare function SetBlipRoute(blip: number, enabled: boolean): void;
declare function BeginTextCommandSetBlipName(textLabel: string): void;
declare function AddTextComponentString(text: string): void;
declare function EndTextCommandSetBlipName(blip: number): void;
declare function exports(exportName: string, handler: (...args: any[]) => any): void;
