const Config = Object.freeze({
  frameworkName: 'Rumble',
  version: '0.8.5',
  defaultCash: Math.max(0, GetConvarInt('rumble_default_cash', 500)),
  defaultCard: Math.max(0, GetConvarInt('rumble_default_card', 5000)),
  maxMoney: Math.max(100000, GetConvarInt('rumble_max_money', 2000000000)),
  maxCharacters: Math.max(1, GetConvarInt('rumble_max_characters', 5)),
  autosaveIntervalMs: Math.max(10000, GetConvarInt('rumble_autosave_interval_ms', 30000)),
  needsIntervalMs: Math.max(10000, GetConvarInt('rumble_needs_interval_ms', 60000)),
  hungerDecay: Math.max(0, GetConvarInt('rumble_hunger_decay', 1)),
  thirstDecay: Math.max(0, GetConvarInt('rumble_thirst_decay', 1)),
  starvationDamage: Math.max(0, GetConvarInt('rumble_starvation_damage', 5)),
  dehydrationDamage: Math.max(0, GetConvarInt('rumble_dehydration_damage', 5)),
  inventoryMaxWeight: Math.max(1000, GetConvarInt('rumble_inventory_max_weight', 30000)),
  inventoryMaxSlots: Math.max(10, GetConvarInt('rumble_inventory_max_slots', 40)),
  maxItemOperation: Math.max(1, GetConvarInt('rumble_max_item_operation', 1000)),
  deathDeadAfterMs: Math.max(10000, GetConvarInt('rumble_death_dead_after_ms', 60000)),
  adminIdentifier: GetConvar('rumble_admin_identifier', '').trim(),
  maxRpcPayloadBytes: Math.max(1024, GetConvarInt('rumble_max_rpc_payload_bytes', 16384)),
  maxMetadataBytes: Math.max(1024, GetConvarInt('rumble_max_metadata_bytes', 16000)),
  securityLogWindowMs: Math.max(1000, GetConvarInt('rumble_security_log_window_ms', 10000)),
  expectedMigration: 2,
});
